# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    python: python3.8
#files: 'mgm-hurry requirements*.txt tests/*.py user_data/*.json user_data/mgm_tools/* user_data/mgm_tools/mgm_hurry/* user_data/strategies/*MoniGoMani*.py'
# files: |
#     (?x)^(
#         requirements*\.txt
#     )$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        files: \.py$
    -   id: end-of-file-fixer
        files: \.py$
    -   id: check-ast # Simply check whether files parse as valid python.
        files: \.py$
    -   id: check-docstring-first
        files: \.py$
    -   id: check-json
        files: \.json$
    -   id: check-added-large-files
    -   id: check-yaml
        files: \.yml|\.yaml$
    -   id: debug-statements
        files: \.py$
    -   id: name-tests-test
        files: \.py$
    -   id: double-quote-string-fixer
        files: \.py$
    -   id: requirements-txt-fixer
        files: \.txt$
    -   id: check-case-conflict # Check for files with names that would conflict on a case-insensitive filesystem like MacOS HFS+ or Windows FAT.
        files: \.py$
    # -   id: check-docstring-first
    # -   id: check-merge-conflict
    # -   id: detect-private-key
    # -   id: fix-encoding-pragma
    # -   id: pretty-format-json

# Let's consider a uniform autoformatter like Black or Yapf
# -   repo: https://github.com/psf/black
#     rev: 19.3b0
#     hooks:
#     -   id: black
